<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48567" started-at="2019-12-09T18:34:32 IST" finished-at="2019-12-09T18:35:20 IST">
    <groups>
      <group name="cucumber">
        <method signature="Runner.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testrunner.Runner@3c130745]" name="feature" class="testrunner.Runner"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="48567" started-at="2019-12-09T18:34:32 IST" finished-at="2019-12-09T18:35:20 IST">
      <class name="testrunner.Runner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:testrunner.Runner@3c130745]" name="setUpClass" is-config="true" duration-ms="200" started-at="2019-12-09T18:34:32 IST" finished-at="2019-12-09T18:34:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testrunner.Runner@3c130745]" name="feature" duration-ms="48172" started-at="2019-12-09T18:34:32 IST" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-12-09T18:35:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Movie ticket booking movie feature]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at testrunner.Runner.feature(Runner.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at stepdefinitions.MoviePageStepDefinition.userOpensMoviePage(MoviePageStepDefinition.java:27)
at âœ½.Given user opens movie page(moviePage.feature:4)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:testrunner.Runner@3c130745]" name="tearDownClass" is-config="true" duration-ms="8" started-at="2019-12-09T18:35:20 IST" finished-at="2019-12-09T18:35:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testrunner.Runner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
